/**
 * Multilingual UI strings. The bot interface is shown in the user's native
 * language (first: Ukrainian and Russian). NEVER hardcode user-facing text in
 * handlers — add a key here and resolve it via `t(lang, key)`.
 *
 * Note: these are *interface* strings. The Portuguese teaching content itself
 * is generated by the LLM, not stored here.
 */

export type UiLanguage = "uk" | "ru";

export const DEFAULT_LANGUAGE: UiLanguage = "uk";

export type StringKey =
  | "welcome"
  | "welcome_pick_language"
  | "menu_mode_words"
  | "menu_mode_sentences"
  | "menu_mode_conversation"
  | "help"
  | "not_implemented_yet"
  | "send_voice_hint"
  | "voice_menu_title"
  | "voice_changed"
  | "menu_mode_practice"
  | "practice_intro"
  | "practice_send_hint"
  | "practice_next_btn"
  | "practice_free_btn"
  | "practice_free_on"
  | "error_generic";

type Pack = Record<StringKey, string>;

const uk: Pack = {
  welcome:
    "👋 Вітаю! Я допоможу вивчати європейську португальську (pt-PT) — " +
    "переклад, правопис, наголоси та розмовна практика голосом.",
  welcome_pick_language: "Оберіть мову інтерфейсу:",
  menu_mode_words: "🗣 Слова та наголоси",
  menu_mode_sentences: "🧩 Побудова речень",
  menu_mode_conversation: "💬 Розмова",
  help:
    "Команди:\n/start — почати\n/practice — повтори за мною (слово)\n" +
    "/voice — обрати голос диктора\n/help — допомога\n\n" +
    "Надсилайте голосові — і я перевірю вимову та наголоси.",
  not_implemented_yet: "⚙️ Цей режим ще в розробці. Незабаром!",
  send_voice_hint: "🎙 Надішліть голосове повідомлення зі словом португальською.",
  voice_menu_title: "🔊 Оберіть голос диктора:",
  voice_changed: "✅ Голос диктора змінено:",
  menu_mode_practice: "🔁 Повтори за мною",
  practice_intro: "🔁 Повтори за мною:",
  practice_send_hint: "Надішли голосове, як ти це вимовляєш 👇",
  practice_next_btn: "▶️ Наступне слово",
  practice_free_btn: "⏹ Вільна практика",
  practice_free_on: "Гаразд, вільна практика. Надсилай будь-яке слово голосом.",
  error_generic: "⚠️ Сталася помилка. Спробуйте ще раз.",
};

const ru: Pack = {
  welcome:
    "👋 Привет! Помогу учить европейский португальский (pt-PT) — " +
    "перевод, правописание, ударения и разговорную практику голосом.",
  welcome_pick_language: "Выберите язык интерфейса:",
  menu_mode_words: "🗣 Слова и ударения",
  menu_mode_sentences: "🧩 Построение предложений",
  menu_mode_conversation: "💬 Разговор",
  help:
    "Команды:\n/start — начать\n/practice — повтори за мной (слово)\n" +
    "/voice — выбрать голос диктора\n/help — помощь\n\n" +
    "Присылайте голосовые — и я проверю произношение и ударения.",
  not_implemented_yet: "⚙️ Этот режим ещё в разработке. Скоро!",
  send_voice_hint: "🎙 Пришлите голосовое сообщение со словом на португальском.",
  voice_menu_title: "🔊 Выберите голос диктора:",
  voice_changed: "✅ Голос диктора изменён:",
  menu_mode_practice: "🔁 Повтори за мной",
  practice_intro: "🔁 Повтори за мной:",
  practice_send_hint: "Пришли голосовое, как ты это произносишь 👇",
  practice_next_btn: "▶️ Следующее слово",
  practice_free_btn: "⏹ Свободная практика",
  practice_free_on: "Ок, свободная практика. Присылай любое слово голосом.",
  error_generic: "⚠️ Произошла ошибка. Попробуйте ещё раз.",
};

const packs: Record<UiLanguage, Pack> = { uk, ru };

export function t(lang: UiLanguage, key: StringKey): string {
  return packs[lang][key] ?? packs[DEFAULT_LANGUAGE][key];
}

export function isSupportedLanguage(value: string): value is UiLanguage {
  return value === "uk" || value === "ru";
}
